source "https://rubygems.org"

gem "rails", "~> 8.0.0"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "kamal", require: false
gem "thruster", require: false

group :development, :test do
  gem "pry-byebug", "~> 3.10", ">= 3.10.1"
end
