name: Test
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-test
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'versioning:development'
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.2"
          - ruby: "3.3"
          - ruby: head
    steps:
      - uses: actions/checkout@v4
      - name: Load dotenv into workflow
        uses: falti/dotenv-action@v1.1.4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: |
          bundle exec rspec \
            -f RspecJunitFormatter -o ${{ steps.dotenv.outputs.JUNIT_REPORTS_PATH }}/rspec_ruby${{ matrix.ruby }}.xml
      - name: Test ActiveResource
        if: always()
        run: |
          bundle exec rake active_resource_test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5.2.0
        if: always()
        with:
          report_paths: '${{ steps.dotenv.outputs.JUNIT_REPORTS_PATH }}/**/*.xml'
          check_name: ':cold_sweat: Failed Tests for Ruby:${{ matrix.ruby }}'
          fail_on_failure: true
          comment: true
